site_name: "MkDocs Logging"
site_description: "Logging utilities for MkDocs plugins."
site_url: "https://pawamoy.github.io/mkdocs-logging"
repo_url: "https://github.com/pawamoy/mkdocs-logging"
repo_name: "pawamoy/mkdocs-logging"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/mkdocs_logging]
copyright: Copyright &copy; 2023 Timothée Mazzucotelli

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
- Author's website: https://pawamoy.github.io/

theme:
  name: material
  custom_dir: docs/.overrides
  icon:
    logo: material/currency-sign
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: "¤"

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - scripts/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.txt
- coverage
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          separate_signature: true
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
- git-committers:
    enabled: !ENV [DEPLOY, false]
    repository: pawamoy/mkdocs-logging

- minify:
    minify_html: !ENV [DEPLOY, false]

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/mastodon
    link: https://fosstodon.org/@pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
  - icon: fontawesome/brands/gitter
    link: https://gitter.im/mkdocs-logging/community
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/mkdocs-logging/
